---
version: 2
updates:
  # Check updates to action versions in .github/workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week on Saturday
      interval: "weekly"
      day: "saturday"
  - package-ecosystem: "gomod"
    directories:
      - "src/cloud-api-adaptor"
      - "src/cloud-api-adaptor/podvm"
      - "src/cloud-providers"
      - "src/csi-wrapper"
      - "src/peerpod-ctrl"
      - "src/webhook"
    open-pull-requests-limit: 100
    groups:
      k8s:
        patterns:
          - "*k8s.io*"
      x/crypto:
        patterns:
          - golang.org/x/crypto
      x/net:
        patterns:
          - golang.org/x/net
      x/sys:
        patterns:
          - golang.org/x/sys
    schedule:
      interval: "daily"
