apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: peerpodconfig-ctrl-caa-daemon
  namespace: confidential-containers-system
  labels:
    name: peerpodconfig-ctrl-caa-daemon
spec:
  template:
    spec:
      containers:
        - name: caa-pod
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: docker-socket
            - mountPath: /var/lib/docker
              name: docker-dir
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: docker-dir
          hostPath:
            path: /var/lib/docker
# to apply this uncomment the patchesStrategicMerge of this file in kustomization.yaml
