apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: peerpodconfig-ctrl-caa-daemon
  namespace: confidential-containers-system
  labels:
    name: peerpodconfig-ctrl-caa-daemon
spec:
  template:
    spec:
      containers:
        - name: caa-pod
          volumeMounts:
            - mountPath: /etc/certificates
              name: certs
      volumes:
        - name: certs
          secret:
            secretName: certs-for-tls
# to apply this uncomment the patchesStrategicMerge of this file in kustomization.yaml
