apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: peerpodconfig-ctrl-caa-daemon
  namespace: confidential-containers-system
  labels:
    name: peerpodconfig-ctrl-caa-daemon
spec:
  template:
    spec:
      containers:
        - name: caa-pod
          volumeMounts:
            - mountPath: /run/kata-containers/shared/direct-volumes
              name: kata-direct-volumes-dir
      volumes:
        - name: kata-direct-volumes-dir
          hostPath:
            path: /run/kata-containers/shared/direct-volumes
            type: DirectoryOrCreate
